# Generated by Django 5.2.6 on 2025-09-10 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apartamento_aviso_morador_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='avisos/'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Taxa condominial', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_comum', models.CharField(help_text='Ex: Salão de Festas, Churrasqueira', max_length=100)),
                ('data_reserva', models.DateField()),
                ('status', models.CharField(default='Confirmada', max_length=50)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.morador')),
            ],
        ),
    ]
